"""Render a Jaeger-style trace visualization for the Day-30 deliverable
(Phase 6 — Production Polish).

The Phase-6 demo story wants a visible "look, here's the trace for one
customer event flowing through the system end-to-end" artifact. The
real article is Jaeger at http://localhost:16686 once the OTel overlay
is up. This script produces the **static** version of that artifact
that lives in `results/samples/` so the repo doesn't depend on a
running Jaeger to surface the headline visualisation.

The trace is generated by actually running an event through the
pipeline under an `InMemorySpanExporter`, then rendering the captured
spans as a horizontal-bar Gantt chart matching Jaeger's visual
convention. So the artifact is a real measurement of the system's
production span graph, not a hand-drawn diagram.

Output:
    results/samples/day30_phase6_jaeger_trace.png
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

# Make the repo importable when running this script directly.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _generate_trace_spans() -> list:
    """Run one synthetic event through the pipeline under an in-memory
    span exporter, return the finished spans."""
    from opentelemetry import trace
    from opentelemetry.sdk.resources import Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import SimpleSpanProcessor
    from opentelemetry.sdk.trace.export.in_memory_span_exporter import (
        InMemorySpanExporter,
    )

    exporter = InMemorySpanExporter()
    provider = TracerProvider(
        resource=Resource.create({"service.name": "pennycore-demo"})
    )
    provider.add_span_processor(SimpleSpanProcessor(exporter))
    trace.set_tracer_provider(provider)

    from contracts.actions import ActionProposal, ActionType, ProposedBy
    from contracts import ChannelType, Event, EventType
    from contracts.observability import trace_span
    from context_engine.event_bus import InMemoryEventBus
    from context_engine.ingestion import ingest_event
    from context_engine.repository import InMemoryEventRepository
    from orchestrator.decision_pipeline import make_default_pipeline

    # Open a parent span so ingest + decide + execute roll up into one
    # Jaeger-style trace (otherwise each call would be its own trace).
    with trace_span(
        "pennycore.event.flow",
        tenant_id="tenant_acme_bank",
        attributes={"pennycore.demo": "jane_mortgage"},
    ):
        repo = InMemoryEventRepository()
        bus = InMemoryEventBus()
        event = Event(
            id="evt_jane_doc_upload",
            tenant_id="tenant_acme_bank",
            customer_id="cus_jane_doe",
            channel_code=ChannelType.API,
            event_type=EventType.DOCUMENT_UPLOADED,
            idempotency_key="idem_jane_001",
            payload={"document_type": "paystub"},
            received_at=datetime.now(timezone.utc),
        )
        ingest_event(event, repo=repo, bus=bus)

        pipeline = make_default_pipeline()
        pipeline.policy.set_policies(
            "tenant_acme_bank",
            {"send_borrower_message": "auto"},
        )
        proposal = ActionProposal(
            id="pp_jane_ack",
            tenant_id="tenant_acme_bank",
            event_id=event.id,
            customer_id=event.customer_id,
            action_type=ActionType.SEND_BORROWER_MESSAGE,
            proposed_by=ProposedBy.FALLBACK,
            payload={"_planner_reasoning": "acknowledge document receipt"},
        )
        pipeline.handle_proposal(proposal)

    return exporter.get_finished_spans()


def _render_trace_png(spans, out_path: Path) -> None:
    """Render the captured spans as a Jaeger-style horizontal Gantt
    chart."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.patches as patches
    import matplotlib.pyplot as plt

    if not spans:
        raise RuntimeError("no spans captured — instrumentation may have broken")

    earliest_start = min(s.start_time for s in spans)
    spans_sorted = sorted(spans, key=lambda s: s.start_time)

    rows = []
    for span in spans_sorted:
        start_us = (span.start_time - earliest_start) / 1000  # ns → µs
        dur_us = (span.end_time - span.start_time) / 1000
        rows.append(
            {
                "name": span.name,
                "start": start_us,
                "duration": max(dur_us, 0.5),
                "attrs": dict(span.attributes),
            }
        )

    fig, ax = plt.subplots(figsize=(14, 7))
    fig.suptitle(
        "PennyCore — OpenTelemetry trace for one customer event\n"
        "Event: document_uploaded (Jane's mortgage paystub) | "
        "tenant: tenant_acme_bank",
        fontsize=13,
        fontweight="bold",
    )

    palette = {
        "pennycore.event.flow": "#3b6cd9",
        "pennycore.ingest_event": "#1e8a4a",
        "pennycore.decision.handle_proposal": "#b85e00",
        "pennycore.executor.execute": "#9b2c2c",
    }

    for i, row in enumerate(rows):
        color = palette.get(row["name"], "#666666")
        ax.add_patch(
            patches.Rectangle(
                (row["start"], i - 0.4),
                row["duration"],
                0.8,
                facecolor=color,
                edgecolor="black",
                alpha=0.85,
                linewidth=1.0,
            )
        )
        label = f" {row['name']}  ({row['duration']:.1f} µs)"
        ax.text(
            row["start"] + row["duration"],
            i,
            label,
            va="center",
            ha="left",
            fontsize=9,
            fontfamily="monospace",
        )

    ax.set_yticks(range(len(rows)))
    ax.set_yticklabels(
        [r["name"].replace("pennycore.", "") for r in rows],
        fontfamily="monospace",
    )
    ax.set_xlabel("Time relative to trace start (µs)", fontsize=11)
    ax.set_xlim(left=0, right=max(r["start"] + r["duration"] for r in rows) * 1.6)
    ax.set_ylim(-1, len(rows))
    ax.invert_yaxis()
    ax.grid(axis="x", alpha=0.3)
    ax.set_axisbelow(True)

    legend_text = (
        "Span attributes captured (selection):\n"
        f"  tenant_id        = {rows[1]['attrs'].get('pennycore.tenant_id', '—')}\n"
        f"  event_id         = {rows[1]['attrs'].get('pennycore.event_id', '—')}\n"
        f"  event_type       = {rows[1]['attrs'].get('pennycore.event_type', '—')}\n"
        f"  decision         = {next((r['attrs'].get('pennycore.decision') for r in rows if 'pennycore.decision' in r['attrs']), '—')}\n"
        f"  action_id        = {next((r['attrs'].get('pennycore.action_id') for r in rows if 'pennycore.action_id' in r['attrs']), '—')}\n"
        f"  action_type      = {next((r['attrs'].get('pennycore.action_type') for r in rows if 'pennycore.action_type' in r['attrs']), '—')}\n"
        f"  executed         = {next((r['attrs'].get('pennycore.executed') for r in rows if 'pennycore.executed' in r['attrs']), '—')}\n"
    )
    fig.text(
        0.5,
        0.02,
        legend_text,
        fontsize=9,
        fontfamily="monospace",
        bbox={"facecolor": "#f7f7f7", "edgecolor": "#999999", "pad": 8},
        ha="center",
    )

    plt.tight_layout(rect=[0, 0.18, 1, 0.94])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=130, facecolor="white")
    plt.close(fig)
    print(f"rendered {out_path}")


def main() -> int:
    os.environ.pop("OTEL_EXPORTER_OTLP_ENDPOINT", None)
    spans = _generate_trace_spans()
    out_path = ROOT / "results" / "samples" / "day30_phase6_jaeger_trace.png"
    _render_trace_png(spans, out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
